# Generated by Django 5.2.3 on 2025-06-16 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_de_compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Compras',
                'verbose_name_plural': 'Listas de Compras',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemListaDeCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidade_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('preco_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprado', models.BooleanField(default=False)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_da_lista', to='financas.listadecompras')),
            ],
            options={
                'verbose_name': 'Item da Lista',
                'verbose_name_plural': 'Itens da Lista',
                'ordering': ['nome'],
            },
        ),
    ]
